# Title: Start Simulation

# Controller Settings
ORYZA_CORE = "./oryza/ORYZA3.exe" # Should be moved to app
NWORKERS    = 2

SCHEMA_SELECTED = "ProtoRun01" 
schema.dir <- paste0("./schemas/", SCHEMA_SELECTED)

load(paste0(schema.dir, "/config.rdata"))
source("./modules/RerunBuilder.R")

library(rstudioapi)
library(terra)

rst.schemaoi <- rast(paste0(schema.dir, "/baseraster.tif"))
if(SCHEMA_WTHSRC=="agera5"){
  rst.wth <- rast()
  names(rst.wth) <- "cdsag" # TODO: Add option for user to specify this
  res(rst.wth) <- 0.1
  values(rst.wth) <- 1:ncell(rst.wth)
}
workers <- vector()
for(i in 1:NWORKERS){
  worker <- paste0(as.numeric(Sys.Date()), ".", i)
  # Create Worker dir and copy ORYZA files
  if(dir.create(paste0(schema.dir, "/", worker), recursive = TRUE)){
    file.copy(ORYZA_CORE, paste(schema.dir, worker, basename(ORYZA_CORE), sep="/")) # ORYZA Exectutable
    file.copy(paste(schema.dir, "CONTROL.DAT", sep="/"), paste(schema.dir, worker, "CONTROL.DAT", sep="/")) # CONTROL.DAT
    file.copy(SCHEMA_CULTIFILE, paste(schema.dir, worker, basename(SCHEMA_CULTIFILE), sep="/")) # Cultivar File
    file.copy(SCHEMA_EXPFILE, paste(schema.dir, worker, basename(SCHEMA_EXPFILE), sep="/")) # Experiment File
    
    # Set Worker status
    saveRDS("ready", file=paste(schema.dir, worker, "status.rds", sep="/"))
  }
  workers <- c(workers, worker)
}


dat.schemaprog <- readRDS(paste0(schema.dir, "/progress_DF.rds"))
# if("cell" %in% colnames(dat.schemaprog)){
#   
# }
# Use while-Loop 
# will continue to run until interrupted or when schema is fully executed
while (length(grep("available", dat.schemaprog$status)) > 0) {
  # Check if job is available
  job.available <- which(dat.schemaprog$status == "available")[1]
  
  if(length(job.available)==1){
    # Identify Soil file
    # ATM, assumption is Soil files are pre-generated. Possible to have an option to create soilfile as jobs are run
    # Can also be generated by schema, but prone to duplication
    job.soilfile <-sprintf("./data/soil/Can Tho/soilgrids_x%0.7f_y%0.7f.sol", round(dat.schemaprog$x[job.available],7), round(dat.schemaprog$y[job.available],7))
    
    if(!file.exists(job.soilfile)){
      dat.schemaprog$status[job.available] <- "discard"
      saveRDS(dat.schemaprog, file = paste(schema.dir, "/progress_DF.rds", sep="/"))
      next
    }
    stop()
    for(i in seq_along(workers)){
      #thisworker.status <- 
      if(readRDS(paste0(schema.dir, "/", workers[i], "/status.rds")) == "ready"){
        dat.schemaprog$status[job.available] <- "delegated"
        dat.schemaprog$run.sttime[job.available] <- Sys.time()
        saveRDS(dat.schemaprog, file = paste(schema.dir, "/progress_DF.rds", sep="/"))
        saveRDS("commissioned", file = paste0(schema.dir, "/", workers[i], "/status.rds"))
        
        file.copy(job.soilfile, paste(schema.dir, workers[i], paste0(SCHEMA_NAME,".sol"), sep="/")) # Experiment File
        
        saveRDS(dat.schemaprog[job.available,], file = paste0(schema.dir, "/",workers[i], "/job.rds"))
        
        # Rerun File
        if(SCHEMA_WTHSRC=="agera5") {
          wthcell <- cellFromXY(rst.wth, dat.schemaprog[job.available, c("x", "y")])
          
          job_rerunparams <- c(SCHEMA_RERUNPARAMS, 
                                  list(ISTN=wthcell,
                                       IYEAR=SCHEMA_STARTYEAR:SCHEMA_ENDYEAR,
                                       STTIME=factor(paste0(SCHEMA_PLANTDOY,"."), levels=paste0(SCHEMA_PLANTDOY,".")) 
                                       ))
          dat.reruns <- writeRerun(job_rerunparams, filename = paste(schema.dir, workers[i], paste0(SCHEMA_NAME, ".rer"),sep="/"))
        }
        
        
        
        rstudioapi::jobRunScript(
          "./modules/Worker.R",
          name = paste(SCHEMA_NAME, workers[i]),
          encoding = "unknown",
          workingDir = paste0(schema.dir, "/",workers[i]),
          importEnv = FALSE,
          exportEnv = ""
        )  
        break # Go find another job
      } else {
        stop()
        # TODO: Update status of current worker and its job
      }
    }
  }
}
    
#   } else {
#     message(SCHEMA_SELECTED, ": Job for", dat.schemaprog$cell[i], " ", dat.schemaprog$status[i], ".", appendLF=TRUE)
#     if(dat.schemaprog$status[i]=="error") {
#       message("Check input files in the Dump.")
#     } else {
#       #TODO: 
#     }
#   }
# 
# }

# Clean-up ----
# Delete worker files
sapply(paste0(schema.dir, "/", workers), unlink, recursive=TRUE)
saveRDS(Sys.Date(),file = paste0(schema.dir, "/schema_lastrun.rds"))
